services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: battleship
      POSTGRES_PASSWORD: battleship
      POSTGRES_DB: battleship