"""add status in GameSessions and shots

Revision ID: 58309ea0306a
Revises: 7f8f3fc5ca1f
Create Date: 2026-09-21 17:53:08.721948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58309ea0306a'
down_revision: Union[str, Sequence[str], None] = '7f8f3fc5ca1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.CheckConstraint("side IN ('self', 'opponent')", name='ck_shots_side'),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'game_sessions',
        sa.Column(
            'status',
            sa.String(length=10),
            nullable=False,
            server_default='opened',
        ),
    )

    op.create_check_constraint(
        'ck_game_sessions_status',
        'game_sessions',
        "status IN ('opened', 'closed')",
    )

    op.alter_column(
        'game_sessions',
        'status',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем таблицу выстрелов
    op.drop_table('shots')

    # Удаляем ограничение для статуса игры
    op.drop_constraint(
        'ck_game_sessions_status',
        'game_sessions',
        type_='check',
    )

    # Удаляем сам столбец status
    op.drop_column('game_sessions', 'status')
